import { Stage } from './types';

export type StageIsland = {
  id: Stage['islandId'];
  title: string;
  description: string;
  stageSetTitles: string[];
};

export const STAGE_ISLANDS: StageIsland[] = [
  {
    id: 'addition',
    title: '足し算の島',
    description: 'あわせて、ぴったりの数をつくる',
    stageSetTitles: ['10の塔', '20の丘', '大きな数の広場'],
  },
  {
    id: 'subtraction',
    title: '引き算の島',
    description: 'なくなるまるを見ながら、差をつくる',
    stageSetTitles: ['10にもどす道'],
  },
];

export const STAGES: Stage[] = [
  {
    id: 'addition-10-ones',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  },
  {
    id: 'addition-10-twos',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [2, 2, 2, 2, 2],
  },
  {
    id: 'addition-10-five-five',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [5, 5],
  },
  {
    id: 'addition-10-six-four',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [6, 4],
  },
  {
    id: 'addition-10-four-six',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [4, 6],
  },
  {
    id: 'addition-10-seven-three',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [7, 3],
  },
  {
    id: 'addition-10-three-seven',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [3, 7],
  },
  {
    id: 'addition-10-eight-two',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [8, 2],
  },
  {
    id: 'addition-10-two-eight',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [2, 8],
  },
  {
    id: 'addition-10-nine-one',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [9, 1],
  },
  {
    id: 'addition-10-one-nine',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [1, 9],
  },
  {
    id: 'addition-10-three-two-five',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [3, 2, 5],
  },
  {
    id: 'addition-10-two-three-five',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [2, 3, 5],
  },
  {
    id: 'addition-10-four-one-five',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [4, 1, 5],
  },
  {
    id: 'addition-10-one-four-five',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [1, 4, 5],
  },
  {
    id: 'addition-10-six-two-two',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [6, 2, 2],
  },
  {
    id: 'addition-10-two-two-six',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [2, 2, 6],
  },
  {
    id: 'addition-10-seven-one-two',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [7, 1, 2],
  },
  {
    id: 'addition-10-one-two-seven',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [1, 2, 7],
  },
  {
    id: 'addition-10-four-three-two-one',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '10の塔',
    bubbleCounts: [4, 3, 2, 1],
  },
  {
    id: 'addition-20-pairs',
    title: '20をつくろう',
    target: 20,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '20の丘',
    bubbleCounts: [6, 4, 7, 3],
  },
  {
    id: 'addition-20-fives',
    title: '20をつくろう',
    target: 20,
    allowedValues: [1],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '20の丘',
    bubbleCounts: [5, 5, 5, 5],
  },
  {
    id: 'addition-50-times',
    title: '50をつくろう',
    target: 50,
    allowedValues: [1, 10],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '大きな数の広場',
    bubbleCounts: [6, 4, 5],
  },
  {
    id: 'addition-100-times',
    title: '100をつくろう',
    target: 100,
    allowedValues: [1, 10],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '大きな数の広場',
    bubbleCounts: [6, 4, 10],
  },
  {
    id: 'addition-120-times',
    title: '120をつくろう',
    target: 120,
    allowedValues: [1, 10, 100],
    islandId: 'addition',
    islandTitle: '足し算の島',
    setTitle: '大きな数の広場',
    bubbleCounts: [6, 4, 3, 4],
  },
  {
    id: 'subtraction-10-minus-two',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'subtraction',
    islandTitle: '引き算の島',
    setTitle: '10にもどす道',
    bubbleCounts: [12, 2],
  },
  {
    id: 'subtraction-10-minus-five',
    title: '10をつくろう',
    target: 10,
    allowedValues: [1],
    islandId: 'subtraction',
    islandTitle: '引き算の島',
    setTitle: '10にもどす道',
    bubbleCounts: [15, 5],
  },
  {
    id: 'subtraction-20-minus-ten',
    title: '20をつくろう',
    target: 20,
    allowedValues: [1, 10],
    islandId: 'subtraction',
    islandTitle: '引き算の島',
    setTitle: '10にもどす道',
    bubbleCounts: [30, 10],
  },
];

export function getStage(index: number) {
  return STAGES[Math.max(0, Math.min(index, STAGES.length - 1))];
}

export function getStageIndexById(stageId: string) {
  return Math.max(0, STAGES.findIndex((stage) => stage.id === stageId));
}
